# Generated by Django 6.1.1 on 2026-09-02 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='departments.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='CITIZEN', max_length=20),
        ),
    ]
