# Generated by Django 6.1.1 on 2026-09-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_department_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_for_assignments',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
