# Generated by Django 6.1.1 on 2026-09-24 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('departments', '0001_initial'),
        ('requests', '0002_requesthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='event_type',
            field=models.CharField(choices=[('STATUS_CHANGED', 'Status Changed'), ('RECLASSIFIED', 'Reclassified')], default='STATUS_CHANGED', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='new_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_request_histories', to='categories.category'),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='new_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_department_histories', to='departments.department'),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='old_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_request_histories', to='categories.category'),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='old_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_department_histories', to='departments.department'),
        ),
    ]
